### ISSUE TITLE
time_coverage_start is skipped if time_coverage_end is missing

### ISSUE THREAD

**Issue by ferrighi** [steingod/mdharvest#28]
in nc_to_mmd we have:

`if 'time_coverage_start' in global_attributes and 'time_coverage_end' in global_attributes:
       self.add_temporal_extent(root, ns_map, ncin)`

But it is allowed to have only time_coverage_start. We could remove "and time_coverage_end", since both are tested in the function adding temporal extent. I'm not sure it's reasonable to have only time_coverage_end, if so we can just change "and" with "or".

**Comment by steingod** [comment]
I think this is covered in the last update.
