### ISSUE TITLE
ds.url.replace in traverse_thredds can replace valid string parts

### ISSUE THREAD

**Issue by ferrighi** [steingod/mdharvest#32]
On traverse thredds: 

https://github.com/steingod/mdharvest/blob/master/src/mdh_modules/traverse_thredds_utils.py#L231

landing page url is populated replacing xml with html, but "xml" can be a valid string in the url 
(e.g. .../subcatalogs/archive.**xml**?dataset=o**xml**roh )

We need to change:
related_information_resource.text = ds.url.replace('xml','html')
with 
related_information_resource.text = ds.url.replace('.xml','.html')

**Comment by steingod** [comment]
Seems to work fine, closing for now.
