### ISSUE TITLE
missing some imports after restructuring

### ISSUE THREAD

**Issue by ferrighi** [steingod/mdharvest#38]
In main branch traverse thredds is currently missing some module imports to work.

Example: ./traverse_thredds -l mylog https://thredds.met.no/thredds/catalog/arcticdata/frost2netcdf-fixed/SN99938/2024/catalog.html .

- NameError: name 'os' is not defined
- NameError: name 'logging' is not defined
- NameError: name 'sys' is not defined
- NameError("name 'traverse_thredds' is not defined")
- ...

1. mdh_utils.py should include: os logging sys
2. traverse_thredds should include: from mdh_modules.traverse_thredds_utils import traverse_thredds 
3. traverse_thredds should include the log argument: traverse_thredds(args.starturl, args.dstdir, args.depth, **mylog**)
4. traverse_thredds_utils.py should include: import threddsclient, from mdh_modules.nc_to_mmd, import Nc_to_mmd, import vocab.ControlledVocabulary, import vocab.CFGCMD, import lxml.etree as ET, import uuid, import re, import os
5. traverse_thredds_utils.py should pass mylog: traverse_thredds(mystart, dstdir, mydepth, mylog)

**Comment by steingod** [comment]
I have to check a bit here, as I have not experienced this whether
locally (multiple computers) or PPI. Will come back.

Ø

On Tue, 2024-10-08 at 08:28 -0700, Lara Ferrighi wrote:
> In main branch traverse thredds is currently missing some module
> imports to work.
> Example: ./traverse_thredds -l mylog
> https://thredds.met.no/thredds/catalog/arcticdata/frost2netcdf-fixed/SN99938/2024/catalog.html
> .
>  * NameError: name 'os' is not defined
>  * NameError: name 'logging' is not defined
>  * NameError: name 'sys' is not defined
>  * NameError("name 'traverse_thredds' is not defined")
>  * ...
>    1. mdh_utils.py should include: os logging sys
>    2. traverse_thredds should include: from
> mdh_modules.traverse_thredds_utils import traverse_thredds
>    3. traverse_thredds should include the log argument:
> traverse_thredds(args.starturl, args.dstdir, args.depth, mylog)
>    4. traverse_thredds_utils.py should include: import threddsclient,
> from mdh_modules.nc_to_mmd, import Nc_to_mmd, import
> vocab.ControlledVocabulary, import vocab.CFGCMD, import lxml.etree as
> ET, import uuid, import re, import os
>    5. traverse_thredds_utils.py should pass mylog:
> traverse_thredds(mystart, dstdir, mydepth, mylog)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Dr. Øystein Godøy
Norwegian Meteorological Institute 
P.O.BOX 43, Blindern, N-0313 OSLO, Norway
Ph: (+47) 9802 4433

**Comment by steingod** [comment]
Sorry for the delay, I can confirm this now and will do a direct fix in main today.

**Comment by steingod** [comment]
I have updated main now.
